version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13.4-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db:/app/